name: targets_server
author: Jack Thakar <jack@jackthakar.com>
homepage: http://github.com/dart-targets/targets-server
version: 0.0.1
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    redstone: ">=0.5.21 <0.6.0"
    browser: ">=0.10.0+2 <0.11.0"
    args: ">=0.12.0+2 <0.13.0"
    shelf_static: any
    grinder: any
    path: "^1.3.5"
    redstone_mapper_pg: any
