name: targets_server
author: Jack Thakar <jack@jackthakar.com>
homepage: http://github.com/dart-targets/targets-server
version: 0.0.1
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    redstone: ">=0.5.21 <0.6.0"
    browser: ">=0.10.0+2 <0.11.0"
    args: ">=0.12.0+2 <0.13.0"
    shelf_static: any
    http: "^0.11.3"
    grinder: any
    path: "^1.3.5"
    crypto: "^0.9.0"
    uuid: "^0.5.0"
    ace: "^0.6.2+3.4.15"
    tree_component:
        git:
            git@github.com:dart-targets/tree_component.git
    redstone_mapper_pg:
        git:
            git@github.com:dart-targets/redstone_mapper_pg.git